name = "tabready"
main = "worker.js"
compatibility_date = "2025-01-01"
account_id = "26c8013cfb2cf72dde19e55e6cf390b1"

[[d1_databases]]
binding = "DB"
database_name = "tabready"
database_id = "dcadb25c-d503-45a7-9e29-254c2d5f50e5"

[[d1_databases]]
binding = "CONTENT_DB"
database_name = "compass"
database_id = "e1f6fdfe-8f59-4799-b112-995c3250c2d2"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "tabready-photos"
